version: "3.7"

services:
  postgres:
    image: "docker.io/library/postgres:12"
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "/mnt/data/postgres:/var/lib/postgresql/data"

  redis:
    image: "docker.io/library/redis:7"

  quay:
    image: "quay.io/projectquay/quay:3.8.8"
    ports:
      - "8080:8080"
    volumes:
      - "/mnt/data/config:/quay-registry/conf/stack"
      - "/mnt/data/registry:/datastorage/registry"
