name: build
on: [ push ]
jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        nix build -vL .#appimage
